---
id: docs-r-l-o-ja-202406
base_name: docs-ruby-lang-org-ja
tags:
- ruby
presentation_date: '2024-06-13'
presentation_start_time:
presentation_end_time:
version: 2024.6.13.0
licenses: []
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 800
height: 600
source_code_uri:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
